#!/bin/bash
# https://stackoverflow.com/a/38732187/1935918
set -e

load_secret_variables() {
  local prefix="$1"
  for i in /run/secrets/*; do
    var=${i#/run/secrets/${prefix}_};
    echo "Defining secret $var";
    export ${var}=$(< $i);
    #echo "$var=${!var}"
  done
}

load_secret_variables "MESDEMARCHES_VAR"

exec "$@"
