#!/bin/bash
# https://stackoverflow.com/a/38732187/1935918
set -e

load_secret_variables() {
  local prefix="/run/secrets/${1}_"

  for i in /run/secrets/*; do
    if [[ "$i" =~ ${prefix}.* ]]
    then
      var=${i#${prefix}};
      echo "Defining secret $var";
      export ${var}=$(< $i);
      #echo "$var=${!var}"
    fi
  done
}

load_secret_variables "MESDEMARCHES_VAR"

exec "$@"
