#!/bin/bash

# https://stackoverflow.com/a/38732187/1935918
set -e

if [ -f /app/tmp/pids/server.pid ]; then
  rm /app/tmp/pids/server.pid
fi

bundle exec rails swarm:migrate
exec bundle exec rails server -b "0.0.0.0"
